# Example nginx configuration file for a reverse proxy on the host running the accompanied docker-compose file.
#
# HOST_BIND_PORT must match the port specified in the docker-compose file for the nginx service.

server {
    listen                                    443 ssl http2;
    server_name                               pds.exampledomain.com;

    # ssl_certificate -- Assigned by certbot or similar.

    # Reasonable limit for cover art. No audio data is stored but if you encounter issues with uploads, you can increase this value.
    client_max_body_size                      50m;

    location / {
        proxy_pass                            http://127.00.1:HOST_BIND_PORT;
        proxy_http_version                    1.1;

        # Firehose com.atproto.sync.subscribeRepos) is a long lived
        # Websocket connection. proxy_read_timeout and proxy_send_timeout 
        # are set to 7 days to avoid timeouts on this connection.
        proxy_set_header                      Upgrade $http_upgrade;
        proxy_set_header                      Connection "upgrade";
        proxy_read_timeout                    7d;
        proxy_send_timeout                    7d;
        proxy_buffering                       off;

        proxy_set_header HOST                 $host;
        proxy_set_header X-Real-IP            $remote_addr;
        proxy_set_header X-Forwarded-For      $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto    $scheme;
    }
}